name: PlatformIO CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project LILYGO-T-Dongle-S3 
        run: pio run --environment LILYGO-T-Dongle-S3 

      - name: Upload LILYGO-T-Dongle-S3 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LILYGO-T-Dongle-S3 Firmware binaries
          path: .pio/build/LILYGO-T-Dongle-S3/*.bin
